global_frame: map

update_frequency: 1
publish_frequency: 1
resolution: 0.1
inflater:
  # footprint: [[-0.18, 0.18], [0.18, 0.18], [0.18, -0.18], [-0.18, -0.18]] # for CUBE
  # robot_radius: 0.26
  cost_scaling_factor: 10.0
  inflation_radius: 1.0
  inflate_unknown: true
plugins:
  - name: static_map
    type: "costmap_2d::StaticLayer"
  - name: laser_obstacles
    type: "costmap_2d::ObstacleLayer"
  - name: inflater
    type: "costmap_2d::InflationLayer"
