robot_base_frame: base_link

transform_tolerance: 0.5
footprint: [[-0.185, 0.185], [0.185, 0.185], [0.185, -0.185], [-0.185, -0.185]]
robot_radius: 0.28
footprint_padding: 0.065
laser_obstacles:
  enabled: true
  observation_sources: livox_mark
  combination_method: 1
  livox_mark:
    data_type: LaserScan
    topic: livox/laser
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 1.0 # 0.6
    expected_update_rate: 0.0 # default 0, if not updating at this rate at least, remove from buffer
    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
    inf_is_valid: true # default false, for laser scans
    nan_is_valid: true
    raytrace_range: 5.5
    obstacle_range: 5.0
