global_frame: map

update_frequency: 1
publish_frequency: 1
resolution: 0.1
inflater:
  cost_scaling_factor: 10.0
  inflation_radius: 0.6
  inflate_unknown: true
plugins:
  - name: static_map
    type: "costmap_2d::StaticLayer"
  - name: laser_obstacles
    type: "costmap_2d::ObstacleLayer"
  - name: inflater
    type: "costmap_2d::InflationLayer"
