# Oscillation
oscillation_timeout: 30.0
oscillation_distance: 0.5
# Global planner
planner_frequency: 0.25 # 0.1
# shutdown_costmap: true
planner_patience: 5.0
# Local planner
max_planning_retries: -1
controller_frequency: 10.0
controller_patience: 0.2

footprint: [[-0.35, 0.43], [0.35, 0.43], [0.35, -0.43], [-0.35, -0.43]]

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  layer_names: ["laser_obstacles"]
  reset_distance: 5.0
