# Oscillation
oscillation_timeout: 30.0
oscillation_distance: 0.5
# Global planner
planner_frequency: 0.25 # 0.1
# shutdown_costmap: true
planner_patience: 5.0
# Local planner
max_planning_retries: -1
controller_frequency: 10.0
controller_patience: 0.2

footprint: [[-0.185, 0.185], [0.185, 0.185], [0.185, -0.185], [-0.185, -0.185]]

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "car_maneuver_recovery"
    type: "car_maneuver_recovery/CarManeuverRecovery"
conservative_reset:
  layer_names: ["laser_obstacles"]
  reset_distance: 3.0
car_maneuver_recovery:
  four_wheel_steering: True
  crab_steering: False
  recovery_speed: 0.1
  recovery_steering_angle: 0.4
  wheelbase: 0.1
  escape_cost_threshold: 200
  timeout: 5.0
  display_costs: True
  extra_footprint_padding: 0.2
