# Planner selection
base_global_planner: "navfn/NavfnROS"
NavfnROS:
  # allow_unknown: false  # investigate this
  allow_unknown: true # investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false
